### ISSUE TITLE
Man får en popup om man trycker på ta bort tid.

### ISSUE THREAD

**Issue by viktorjohansson** [Istanful/CubeTimer#21]
Detta borde man inte få. Detta ska inte vara en setting

**Comment by viktorjohansson** [comment]
@Istanful

**Comment by Istanful** [comment]
@viktorjohansson Detta kommer åtgärdas. Eventuellt efter den har blivit portad till rails.

**Comment by Istanful** [comment]
Hej Viktor!

Nu kan du stänga av dialogrutan som visas när du tar bort en tid!
Utan att sätta någon inställning kommer en dialogruta som standard.

För att stänga av dialogrutan:
1. Öppna konsolen. Du kan göra detta genom att högerklicka, välja inspektera och sedan klicka console.
2. Skriv i konsolen: `save.options.viktor = {}; save.options.viktor.confirmTimeDeletion = false`
